FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Train

Train APIs

# Group Battle
バトル画面(クエスト、ステージ制で共通)<br>
SetBattle呼び出し時にバトル処理を行う<br>
ID発行済→setbattle→result→ステータス反映
## Main [/v1/battle/{battle_id}]

### SetBattle [PUT]
+ Response 201 (application/json)


    + Attribute
        + type: quest(string) - quest or stage
        + friend_position (array) - 参戦する自キャラの情報
            + (Char)
        + enemy_position (array) - 参戦する敵キャラの情報
            + (Char)


### turnoverBattle [GET]
+ Response 200 (application/json)


## Result [/v1/battle/result/{battle_id}]
指定されたバトル結果を送信、該当バトルのステータスを終了済みに変更する

### Result[PUT]
+ Response 200 (application/json)


    + Attribute
        + is_win: true(boolean) - 勝ち負け
        + get_item (Item)
        + money: 3150(number) - 所持金額(加算済み)
        + prize: 150(number) - 獲得金額
        + chars (array) - キャラクターのステータス(上昇前)
            + (Char)
        + obtained (array) - キャラクターのステータス(上昇後)
            + (Char)

# Group Gacha
## Gacha [/v1/gacha/]
ガチャ画面
### Check Gacha [GET]
+ Response 200 (application/json)


    + Attribute
        + availability: true(boolean) - ガチャが実行可能かどうか
        + rest_char: 4(number) - 残りキャラ数
        + gacha_cost: 1000(number) - ガチャ実行コスト
        + money: 4800(number) - 所持金

### Draw Gacha [POST]
+ Response 201 (application/json)


    + Attribute
        + char_id: 2(number) - キャラid
        + name: 丑(string) - キャラ名
        + status (Status)

# Group Menu
## Menu [/v1/menu/]

### Get Status [GET]
+ Response 200 (application/json)


    + Attribute
        + name: ほげ(string) - user name
        + money: 3000(number) - 所持金
        + medal: 初心者(string) - 称号
        + leader_char_id: 2(number) - リーダーキャラのID
        + quest_count: 16(number)

# Group Order
## Order [/v1/order/{type}]
### Get Order [GET]
+ Response 200 (application/json)


    + Attribute
        + party (array) - 現在のパーティキャラ及び装備
            + (object)
                + char_id: 3(number) - キャラID
                + item_id: 1(number) - アイテムID
        + chars (array)
            + (Char)
        + items (array)
            + (Item)


### Change Order [PUT]
+ Request (application/json)


    + Attribute
        + slot: 3(number) - 変更するスロット
        + new_id: 6(number) - 変更後のキャラクター

+ Response 201 (application/json)


    + Attribute
        + slot: 3(number) - 変更するスロット
        + new_id: 6(number) - 変更後のキャラクター


# Group Quest
## Quest [/v1/quest/]
クエストバトル発行API
quest属性のbattleidを作成する
### Join: Quest Battle [POST]
+ Response 201 (application/json)

    + Attribute
        + battle_id: 1(number) - バトルID


# Group Stage
## StageMenu [/v1/stage/]
バトル選択画面
stage属性のbattleidを作成する
### Get BattleList [GET]
+ Response 200(application/json)


    + Attribute
        + money: 4800(number) (required)- 所持金
        + chars (array)
            + :
                + char_id: 2(number) - キャラid
                + name: 丑(string) - キャラ名
                + status (Status)

        + stages - ステージ情報
            + stage_id: 1(number) - ステージID
            + title: 初級(string) - ステージ名
            + entry_fee: 100(number) - 参加費
            + prize: 200(number) - 賞金
            + item_name: 初級卒業(string) - 獲得称号
            + clearcount: 3(number) - クリア回数

### Join Arena Battle [POST]
+ Request (application/json)

    + Attribute
        + stage_id: 1(number) - ステージID

+ Response 201 (application/json)

    + Attribute
        + battle_id: 2(number) - バトルID


#Data Structure

## Char
+ char_id: 1(number) - キャラID
+ name: うし(string) - キャラ名
+ level: 4(number) - レベル
+ exp: 50(number) - 経験値
+ status (Status)

## Item
+ item_id: 1(number) - アイテムID
+ name: 初心者(string) - アイテム名
+ text: はじめたて(string) - アイテムの説明
+ status (Status)

## Status
+ attack: 25(number) - 攻撃力
+ endurance: 45(number) - 耐久力
+ agility: 30(number) - 敏捷性
+ debuf: 15(number) - 削減能力